# Tutorial 5: Neural Architecture Search (NAS) with Mase and Optuna

In this tutorial, we'll see how Mase can be integrated with Optuna, the popular hyperparameter optimization framework, to search for a Bert model optimized for sequence classification on the IMDb dataset. We'll take the Optuna-generated model and import it into Mase, then run the CompressionPipeline to prepare the model for edge deployment by quantizing and pruning its weights.

As we'll see, running Architecture Search with Mase/Optuna involves the following steps.

1. **Define the search space**: this is a dictionary containing the range of values for each parameter at each layer in the model.

2. **Write the model constructor**: this is a function which uses Optuna utilities to sample a model from the search space, and constructs the model using transformers from_config class method.

3. **Write the objective function**: this function calls on the model constructor defined in Step 2 and defines the training/evaluation setup for each search iteration.

4. **Go!** Choose an Optuna sampler, create a study and launch the search.

In [2]:
checkpoint = "prajjwal1/bert-tiny"
tokenizer_checkpoint = "bert-base-uncased"
dataset_name = "imdb"

First, fetch the dataset using the `get_tokenized_dataset` utility.

In [3]:
from chop.tools import get_tokenized_dataset

dataset, tokenizer = get_tokenized_dataset(
    dataset=dataset_name,
    checkpoint=tokenizer_checkpoint,
    return_tokenizer=True,
)

/home/roy/Documents/STUDY/IC/YEAR4_TERM2/ADLS/mase/.venv/lib/python3.11/site-packages/torch/cuda/__init__.py:61: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
/home/roy/Documents/STUDY/IC/YEAR4_TERM2/ADLS/mase/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
INFO     Tokenizing dataset imdb with AutoTokenizer for bert-base-uncased.

## 1. Defining the Search Space

We'll start by defining a search space, i.e. enumerating the possible combinations of hyperparameters that Optuna can choose during search. We'll explore the following range of values for the model's hidden size, intermediate size, number of layers and number of heads, inspired by the [NAS-BERT paper](https://arxiv.org/abs/2105.14444).

In [4]:
import torch.nn as nn
from chop.nn.modules import Identity

search_space = {
    "num_layers": [2, 4, 8],
    "num_heads": [2, 4, 8, 16],
    "hidden_size": [128, 192, 256, 384, 512],
    "intermediate_size": [512, 768, 1024, 1536, 2048],
    "linear_layer_choices": [
        nn.Linear,
        Identity,
    ],
}

## 2. Writing a Model Constructor

We define the following function, which will get called in each iteration of the search process. The function is passed the `trial` argument, which is an Optuna object that comes with many functionalities - see the [Trial documentation](https://optuna.readthedocs.io/en/stable/reference/trial.html) for more details. Here, we use the `trial.suggest_int` and `trial.suggest_categorical` functions to trigger the chosen sampler to choose parameter choices and layer types. The suggested integer is the index into the search space for each parameter, which we defined in the previous cell.

In [5]:
from transformers import AutoConfig, AutoModelForSequenceClassification
from chop.tools.utils import deepsetattr


def construct_model(trial):
    config = AutoConfig.from_pretrained(checkpoint)

    # Update the paramaters in the config
    for param in [
        "num_layers",
        "num_heads",
        "hidden_size",
        "intermediate_size",
    ]:
        chosen_idx = trial.suggest_int(param, 0, len(search_space[param]) - 1)
        setattr(config, param, search_space[param][chosen_idx])

    trial_model = AutoModelForSequenceClassification.from_config(config)

    for name, layer in trial_model.named_modules():
        if isinstance(layer, nn.Linear) and layer.in_features == layer.out_features:
            new_layer_cls = trial.suggest_categorical(
                f"{name}_type",
                search_space["linear_layer_choices"],
            )

            if new_layer_cls == nn.Linear:
                continue
            elif new_layer_cls == Identity:
                new_layer = Identity()
                deepsetattr(trial_model, name, new_layer)
            else:
                raise ValueError(f"Unknown layer type: {new_layer_cls}")

    return trial_model

## 3. Defining the Objective Function

Next, we define the objective function for the search, which gets called on each trial. In each trial, we create a new model instace with chosen hyperparameters according to the defined sampler. We then use the `get_trainer` utility in Mase to run a training loop on the IMDb dataset for a number of epochs. Finally, we use `evaluate` to report back the classification accuracy on the test split.

In [6]:
from chop.tools import get_trainer


def objective(trial):

    # Define the model
    model = construct_model(trial)

    trainer = get_trainer(
        model=model,
        tokenized_dataset=dataset,
        tokenizer=tokenizer,
        evaluate_metric="accuracy",
        num_train_epochs=1,
    )

    trainer.train()
    eval_results = trainer.evaluate()

    # Set the model as an attribute so we can fetch it later
    trial.set_user_attr("model", model)

    return eval_results["eval_accuracy"]

## 4. Launching the Search

Optuna provides a number of samplers, for example:

* **GridSampler**: iterates through every possible combination of hyperparameters in the search space
* **RandomSampler**: chooses a random combination of hyperparameters in each iteration
* **TPESampler**: uses Tree-structured Parzen Estimator algorithm to choose hyperparameter values.

You can define the chosen sampler by simply importing from `optuna.samplers` as below.

In [7]:
from optuna.samplers import GridSampler, RandomSampler, TPESampler

sampler = RandomSampler()

With all the pieces in place, we can launch the search as follows. The number of trials is set to 1 so you can go get a coffee for 10 minutes, then proceed with the tutorial. However, this will essentially be a random model - for better results, set this to 100 and leave it running overnight!

In [ ]:
import optuna

study = optuna.create_study(
    direction="maximize",
    study_name="bert-tiny-nas-study",
    sampler=sampler,
)

study.optimize(
    objective,
    n_trials=10,
    timeout=60 * 60 * 24,
    show_progress_bar=True,
)

[I 2026-02-06 16:50:20,346] A new study created in memory with name: bert-tiny-nas-study
  0%|                                                                                                                                                                  | 0/10 [00:00<?, ?it/s]/home/roy/Documents/STUDY/IC/YEAR4_TERM2/ADLS/mase/.venv/lib/python3.11/site-packages/optuna/distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains <class 'torch.nn.modules.linear.Linear'> which is of type type.
  warnings.warn(message)
/home/roy/Documents/STUDY/IC/YEAR4_TERM2/ADLS/mase/.venv/lib/python3.11/site-packages/optuna/distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains <class 'chop.nn.modules.identity.Identity'> which is of type type.
  warnings.warn(message)
/home/roy/Documents/STUDY/IC/YEAR4_TERM2/ADLS/mase/src/chop/tools/huggingface.py:160: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Best trial: 0. Best value: 0.83416:  10%|█████████▋                                                                                       | 1/10 [00:26<03:57, 26.43s/it, 26.42/86400 seconds]/home/roy/Documents/STUDY/IC/YEAR4_TERM2/ADLS/mase/.venv/lib/python3.11/site-packages/optuna/distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains <class 'torch.nn.modules.linear.Linear'> which is of type type.
  warnings.warn(message)
/home/roy/Documents/STUDY/IC/YEAR4_TERM2/ADLS/mase/.venv/lib/python3.11/site-packages/optuna/distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains <class 'chop.nn.modules.identity.Identity'> which is of type type.
  warnings.warn(message)

[I 2026-02-06 16:50:46,769] Trial 0 finished with value: 0.83416 and parameters: {'num_layers': 2, 'num_heads': 1, 'hidden_size': 0, 'intermediate_size': 3, 'bert.encoder.layer.0.attention.self.query_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.0.attention.self.key_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.0.attention.self.value_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.0.attention.output.dense_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.1.attention.self.query_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.1.attention.self.key_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.1.attention.self.value_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.1.attention.output.dense_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.pooler.dense_type': <class 'chop.nn.modules.identity.Identity'>}. Best is trial 0 with value: 0.83416.

/home/roy/Documents/STUDY/IC/YEAR4_TERM2/ADLS/mase/src/chop/tools/huggingface.py:160: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Best trial: 1. Best value: 0.8388:  20%|███████████████████▌                                                                              | 2/10 [00:53<03:35, 26.93s/it, 53.71/86400 seconds]/home/roy/Documents/STUDY/IC/YEAR4_TERM2/ADLS/mase/.venv/lib/python3.11/site-packages/optuna/distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains <class 'torch.nn.modules.linear.Linear'> which is of type type.
  warnings.warn(message)
/home/roy/Documents/STUDY/IC/YEAR4_TERM2/ADLS/mase/.venv/lib/python3.11/site-packages/optuna/distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains <class 'chop.nn.modules.identity.Identity'> which is of type type.
  warnings.warn(message)

[I 2026-02-06 16:51:14,053] Trial 1 finished with value: 0.8388 and parameters: {'num_layers': 0, 'num_heads': 3, 'hidden_size': 0, 'intermediate_size': 4, 'bert.encoder.layer.0.attention.self.query_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.0.attention.self.key_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.0.attention.self.value_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.0.attention.output.dense_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.1.attention.self.query_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.1.attention.self.key_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.1.attention.self.value_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.1.attention.output.dense_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.pooler.dense_type': <class 'torch.nn.modules.linear.Linear'>}. Best is trial 1 with value: 0.8388.

/home/roy/Documents/STUDY/IC/YEAR4_TERM2/ADLS/mase/src/chop/tools/huggingface.py:160: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Best trial: 2. Best value: 0.85208:  30%|█████████████████████████████                                                                    | 3/10 [01:20<03:06, 26.71s/it, 80.15/86400 seconds]

[I 2026-02-06 16:51:40,496] Trial 2 finished with value: 0.85208 and parameters: {'num_layers': 2, 'num_heads': 0, 'hidden_size': 1, 'intermediate_size': 1, 'bert.encoder.layer.0.attention.self.query_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.0.attention.self.key_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.0.attention.self.value_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.0.attention.output.dense_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.1.attention.self.query_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.1.attention.self.key_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.1.attention.self.value_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.1.attention.output.dense_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.pooler.dense_type': <class 'chop.nn.modules.identity.Identity'>}. Best is trial 2 with value: 0.85208.

/home/roy/Documents/STUDY/IC/YEAR4_TERM2/ADLS/mase/.venv/lib/python3.11/site-packages/optuna/distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains <class 'torch.nn.modules.linear.Linear'> which is of type type.
  warnings.warn(message)
/home/roy/Documents/STUDY/IC/YEAR4_TERM2/ADLS/mase/.venv/lib/python3.11/site-packages/optuna/distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains <class 'chop.nn.modules.identity.Identity'> which is of type type.
  warnings.warn(message)
/home/roy/Documents/STUDY/IC/YEAR4_TERM2/ADLS/mase/src/chop/tools/huggingface.py:160: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Best trial: 3. Best value: 0.86624:  40%|██████████████████████████████████████▍                                                         | 4/10 [02:02<03:16, 32.72s/it, 122.08/86400 seconds]/home/roy/Documents/STUDY/IC/YEAR4_TERM2/ADLS/mase/.venv/lib/python3.11/site-packages/optuna/distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains <class 'torch.nn.modules.linear.Linear'> which is of type type.
  warnings.warn(message)
/home/roy/Documents/STUDY/IC/YEAR4_TERM2/ADLS/mase/.venv/lib/python3.11/site-packages/optuna/distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains <class 'chop.nn.modules.identity.Identity'> which is of type type.
  warnings.warn(message)

[I 2026-02-06 16:52:22,427] Trial 3 finished with value: 0.86624 and parameters: {'num_layers': 1, 'num_heads': 0, 'hidden_size': 3, 'intermediate_size': 4, 'bert.encoder.layer.0.attention.self.query_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.0.attention.self.key_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.0.attention.self.value_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.0.attention.output.dense_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.1.attention.self.query_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.1.attention.self.key_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.1.attention.self.value_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.1.attention.output.dense_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.pooler.dense_type': <class 'torch.nn.modules.linear.Linear'>}. Best is trial 3 with value: 0.86624.

/home/roy/Documents/STUDY/IC/YEAR4_TERM2/ADLS/mase/src/chop/tools/huggingface.py:160: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Best trial: 3. Best value: 0.86624:  50%|████████████████████████████████████████████████                                                | 5/10 [02:35<02:44, 32.84s/it, 155.13/86400 seconds]

[I 2026-02-06 16:52:55,479] Trial 4 finished with value: 0.85848 and parameters: {'num_layers': 0, 'num_heads': 3, 'hidden_size': 2, 'intermediate_size': 4, 'bert.encoder.layer.0.attention.self.query_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.0.attention.self.key_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.0.attention.self.value_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.0.attention.output.dense_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.1.attention.self.query_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.1.attention.self.key_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.1.attention.self.value_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.1.attention.output.dense_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.pooler.dense_type': <class 'torch.nn.modules.linear.Linear'>}. Best is trial 3 with value: 0.86624.

/home/roy/Documents/STUDY/IC/YEAR4_TERM2/ADLS/mase/.venv/lib/python3.11/site-packages/optuna/distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains <class 'torch.nn.modules.linear.Linear'> which is of type type.
  warnings.warn(message)
/home/roy/Documents/STUDY/IC/YEAR4_TERM2/ADLS/mase/.venv/lib/python3.11/site-packages/optuna/distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains <class 'chop.nn.modules.identity.Identity'> which is of type type.
  warnings.warn(message)
/home/roy/Documents/STUDY/IC/YEAR4_TERM2/ADLS/mase/src/chop/tools/huggingface.py:160: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Best trial: 3. Best value: 0.86624:  60%|█████████████████████████████████████████████████████████▌                                      | 6/10 [03:10<02:14, 33.56s/it, 190.09/86400 seconds]/home/roy/Documents/STUDY/IC/YEAR4_TERM2/ADLS/mase/.venv/lib/python3.11/site-packages/optuna/distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains <class 'torch.nn.modules.linear.Linear'> which is of type type.
  warnings.warn(message)
/home/roy/Documents/STUDY/IC/YEAR4_TERM2/ADLS/mase/.venv/lib/python3.11/site-packages/optuna/distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains <class 'chop.nn.modules.identity.Identity'> which is of type type.
  warnings.warn(message)

[I 2026-02-06 16:53:30,438] Trial 5 finished with value: 0.84512 and parameters: {'num_layers': 1, 'num_heads': 3, 'hidden_size': 3, 'intermediate_size': 2, 'bert.encoder.layer.0.attention.self.query_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.0.attention.self.key_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.0.attention.self.value_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.0.attention.output.dense_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.1.attention.self.query_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.1.attention.self.key_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.1.attention.self.value_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.1.attention.output.dense_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.pooler.dense_type': <class 'torch.nn.modules.linear.Linear'>}. Best is trial 3 with value: 0.86624.

/home/roy/Documents/STUDY/IC/YEAR4_TERM2/ADLS/mase/src/chop/tools/huggingface.py:160: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Best trial: 3. Best value: 0.86624:  70%|███████████████████████████████████████████████████████████████████▏                            | 7/10 [03:35<01:32, 30.81s/it, 215.25/86400 seconds]

[I 2026-02-06 16:53:55,592] Trial 6 finished with value: 0.8264 and parameters: {'num_layers': 2, 'num_heads': 0, 'hidden_size': 0, 'intermediate_size': 1, 'bert.encoder.layer.0.attention.self.query_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.0.attention.self.key_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.0.attention.self.value_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.0.attention.output.dense_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.1.attention.self.query_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.1.attention.self.key_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.1.attention.self.value_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.1.attention.output.dense_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.pooler.dense_type': <class 'torch.nn.modules.linear.Linear'>}. Best is trial 3 with value: 0.86624.

/home/roy/Documents/STUDY/IC/YEAR4_TERM2/ADLS/mase/.venv/lib/python3.11/site-packages/optuna/distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains <class 'torch.nn.modules.linear.Linear'> which is of type type.
  warnings.warn(message)
/home/roy/Documents/STUDY/IC/YEAR4_TERM2/ADLS/mase/.venv/lib/python3.11/site-packages/optuna/distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains <class 'chop.nn.modules.identity.Identity'> which is of type type.
  warnings.warn(message)
/home/roy/Documents/STUDY/IC/YEAR4_TERM2/ADLS/mase/src/chop/tools/huggingface.py:160: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Best trial: 3. Best value: 0.86624:  80%|████████████████████████████████████████████████████████████████████████████▊                   | 8/10 [04:09<01:04, 32.01s/it, 249.84/86400 seconds]

[I 2026-02-06 16:54:30,184] Trial 7 finished with value: 0.83352 and parameters: {'num_layers': 1, 'num_heads': 0, 'hidden_size': 3, 'intermediate_size': 2, 'bert.encoder.layer.0.attention.self.query_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.0.attention.self.key_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.0.attention.self.value_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.0.attention.output.dense_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.1.attention.self.query_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.1.attention.self.key_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.1.attention.self.value_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.1.attention.output.dense_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.pooler.dense_type': <class 'torch.nn.modules.linear.Linear'>}. Best is trial 3 with value: 0.86624.

/home/roy/Documents/STUDY/IC/YEAR4_TERM2/ADLS/mase/.venv/lib/python3.11/site-packages/optuna/distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains <class 'torch.nn.modules.linear.Linear'> which is of type type.
  warnings.warn(message)
/home/roy/Documents/STUDY/IC/YEAR4_TERM2/ADLS/mase/.venv/lib/python3.11/site-packages/optuna/distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains <class 'chop.nn.modules.identity.Identity'> which is of type type.
  warnings.warn(message)
/home/roy/Documents/STUDY/IC/YEAR4_TERM2/ADLS/mase/src/chop/tools/huggingface.py:160: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Best trial: 3. Best value: 0.86624:  90%|██████████████████████████████████████████████████████████████████████████████████████▍         | 9/10 [04:46<00:33, 33.47s/it, 286.51/86400 seconds]/home/roy/Documents/STUDY/IC/YEAR4_TERM2/ADLS/mase/.venv/lib/python3.11/site-packages/optuna/distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains <class 'torch.nn.modules.linear.Linear'> which is of type type.
  warnings.warn(message)
/home/roy/Documents/STUDY/IC/YEAR4_TERM2/ADLS/mase/.venv/lib/python3.11/site-packages/optuna/distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains <class 'chop.nn.modules.identity.Identity'> which is of type type.
  warnings.warn(message)

[I 2026-02-06 16:55:06,860] Trial 8 finished with value: 0.85568 and parameters: {'num_layers': 2, 'num_heads': 2, 'hidden_size': 4, 'intermediate_size': 0, 'bert.encoder.layer.0.attention.self.query_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.0.attention.self.key_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.0.attention.self.value_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.0.attention.output.dense_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.0.intermediate.dense_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.0.output.dense_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.1.attention.self.query_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.1.attention.self.key_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.1.attention.self.value_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.1.attention.output.dense_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.1.intermediate.dense_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.1.output.dense_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.pooler.dense_type': <class 'chop.nn.modules.identity.Identity'>}. Best is trial 3 with value: 0.86624.

/home/roy/Documents/STUDY/IC/YEAR4_TERM2/ADLS/mase/src/chop/tools/huggingface.py:160: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Best trial: 3. Best value: 0.86624: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [05:13<00:00, 31.34s/it, 313.36/86400 seconds]

[I 2026-02-06 16:55:33,707] Trial 9 finished with value: 0.84404 and parameters: {'num_layers': 1, 'num_heads': 3, 'hidden_size': 1, 'intermediate_size': 2, 'bert.encoder.layer.0.attention.self.query_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.0.attention.self.key_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.0.attention.self.value_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.0.attention.output.dense_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.1.attention.self.query_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.1.attention.self.key_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.1.attention.self.value_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.1.attention.output.dense_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.pooler.dense_type': <class 'torch.nn.modules.linear.Linear'>}. Best is trial 3 with value: 0.86624.

In [9]:
optuna.visualization.plot_optimization_history(study)

Fetch the model associated with the best trial as follows, and export to be used in future tutorials. In Tutorial 6, we'll see how to run mixed-precision quantization search on top of the model we've just found through NAS to further find the optimal quantization mapping.

In [10]:
from pathlib import Path
import dill

model = study.best_trial.user_attrs["model"].cpu()

with open(f"{Path.home()}/tutorial_5_best_model.pkl", "wb") as f:
    dill.dump(model, f)

## Deploying the Optimized Model with CompressionPipeline

Now, we can run the CompressionPipeline in Mase to run uniform quantization and pruning over the searched model.

In [11]:
from chop.pipelines import CompressionPipeline
from chop import MaseGraph

mg = MaseGraph(model)
pipe = CompressionPipeline()

quantization_config = {
    "by": "type",
    "default": {
        "config": {
            "name": None,
        }
    },
    "linear": {
        "config": {
            "name": "integer",
            # data
            "data_in_width": 8,
            "data_in_frac_width": 4,
            # weight
            "weight_width": 8,
            "weight_frac_width": 4,
            # bias
            "bias_width": 8,
            "bias_frac_width": 4,
        }
    },
}

pruning_config = {
    "weight": {
        "sparsity": 0.5,
        "method": "l1-norm",
        "scope": "local",
    },
    "activation": {
        "sparsity": 0.5,
        "method": "l1-norm",
        "scope": "local",
    },
}

mg, _ = pipe(
    mg,
    pass_args={
        "quantize_transform_pass": quantization_config,
        "prune_transform_pass": pruning_config,
    },
)

`past_key_values` were not specified as input names, but model.config.use_cache = True. Setting model.config.use_cache = False.
INFO     Getting dummy input for prajjwal1/bert-tiny.

tensor([[ 101, 9932, 2089, 2202, 2058, 1996, 2088, 2028, 2154,  102],
        [ 101, 2023, 2003, 2339, 2017, 2323, 4553, 4748, 4877,  102]])
tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
tensor([[ 101, 9932, 2089, 2202, 2058, 1996, 2088, 2028, 2154,  102],
        [ 101, 2023, 2003, 2339, 2017, 2323, 4553, 4748, 4877,  102]])
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]]])
tensor([[[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]]])
tensor([[[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]]])
tensor([[[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]]])
tensor([[[-0.2747, -0.3459,  0.0505,  ...,  1.0890,  2.1885, -1.8425],
         [-2.0989,  0.7609, -0.0804,  ...,  1.8929,  2.3537, -0.2067],
         [-1.7011, -0.6241,  0.0595,  ...,  0.8663,  1.8165, -0.6128],
         ...,
         [-1.6867,  0.0732,  0.9994,  ..., -0.4596,  0.7571, -2.0665],
         [ 0.3121,  1.6837, -1.0645,  ...,  1.1077,  1.1985, -1.8642],
         [-0.8974, -0.6339,  0.8265,  ..., -1.2043,  2.0258, -1.4443]],

        [[-0.2747, -0.3459,  0.0505,  ...,  1.0890,  2.1885, -1.8425],
         [-0.8184, -0.2921, -1.5490,  ...,  0.3487,  2.9099, -0.5628],
         [-1.1638, -1.3308,  1.2314,  ...,  0.6622,  1.4889, -1.0370],
         ...,
         [-1.3038,  0.5135,  0.0645,  ..., -0.0068,  2.1404, -1.6559],
         [-0.1842,  1.2361, -0.2287,  ...,  0.2927,  0.9115, -1.1649],
         [-0.8974, -0.6339,  0.8265,  ..., -1.2043,  2.0258, -1.4443]]],
       grad_fn=<NativeLayerNormBackward0>)
tensor([[[-0.2747, -0.3459,  0.0505,  ...,  1.0890,  2.1885, -1.8425],
         [-2.0989,  0.7609, -0.0804,  ...,  1.8929,  2.3537, -0.2067],
         [-1.7011, -0.6241,  0.0595,  ...,  0.8663,  1.8165, -0.6128],
         ...,
         [-1.6867,  0.0732,  0.9994,  ..., -0.4596,  0.7571, -2.0665],
         [ 0.3121,  1.6837, -1.0645,  ...,  1.1077,  1.1985, -1.8642],
         [-0.8974, -0.6339,  0.8265,  ..., -1.2043,  2.0258, -1.4443]],

        [[-0.2747, -0.3459,  0.0505,  ...,  1.0890,  2.1885, -1.8425],
         [-0.8184, -0.2921, -1.5490,  ...,  0.3487,  2.9099, -0.5628],
         [-1.1638, -1.3308,  1.2314,  ...,  0.6622,  1.4889, -1.0370],
         ...,
         [-1.3038,  0.5135,  0.0645,  ..., -0.0068,  2.1404, -1.6559],
         [-0.1842,  1.2361, -0.2287,  ...,  0.2927,  0.9115, -1.1649],
         [-0.8974, -0.6339,  0.8265,  ..., -1.2043,  2.0258, -1.4443]]],
       grad_fn=<NativeLayerNormBackward0>)
tensor([[[-0.2747, -0.3459,  0.0505,  ...,  1.0890,  2.1885, -1.8425],
         [-2.0989,  0.7609, -0.0804,  ...,  1.8929,  2.3537, -0.2067],
         [-1.7011, -0.6241,  0.0595,  ...,  0.8663,  1.8165, -0.6128],
         ...,
         [-1.6867,  0.0732,  0.9994,  ..., -0.4596,  0.7571, -2.0665],
         [ 0.3121,  1.6837, -1.0645,  ...,  1.1077,  1.1985, -1.8642],
         [-0.8974, -0.6339,  0.8265,  ..., -1.2043,  2.0258, -1.4443]],

        [[-0.2747, -0.3459,  0.0505,  ...,  1.0890,  2.1885, -1.8425],
         [-0.8184, -0.2921, -1.5490,  ...,  0.3487,  2.9099, -0.5628],
         [-1.1638, -1.3308,  1.2314,  ...,  0.6622,  1.4889, -1.0370],
         ...,
         [-1.3038,  0.5135,  0.0645,  ..., -0.0068,  2.1404, -1.6559],
         [-0.1842,  1.2361, -0.2287,  ...,  0.2927,  0.9115, -1.1649],
         [-0.8974, -0.6339,  0.8265,  ..., -1.2043,  2.0258, -1.4443]]],
       grad_fn=<NativeLayerNormBackward0>)
tensor([[[[-2.7471e-01, -3.4588e-01,  5.0534e-02,  ...,  1.4485e+00,
           -3.1027e-01, -1.2747e+00],
          [-2.5288e-01,  3.5484e-01,  7.0041e-01,  ...,  1.0890e+00,
            2.1885e+00, -1.8425e+00]],

         [[-2.0989e+00,  7.6092e-01, -8.0434e-02,  ..., -1.8727e+00,
            1.6981e+00, -1.5126e+00],
          [ 3.0126e-01,  2.4590e-01,  1.1417e+00,  ...,  1.8929e+00,
            2.3537e+00, -2.0670e-01]],

         [[-1.7011e+00, -6.2414e-01,  5.9500e-02,  ..., -2.4959e+00,
           -1.9612e-04, -1.9875e+00],
          [ 5.6950e-02,  1.0799e+00, -1.2296e+00,  ...,  8.6632e-01,
            1.8165e+00, -6.1276e-01]],

         ...,

         [[-1.6867e+00,  7.3248e-02,  9.9938e-01,  ..., -5.1200e-01,
            1.6412e+00, -9.3374e-01],
          [ 3.1425e-01, -1.2530e+00, -9.5933e-01,  ..., -4.5960e-01,
            7.5712e-01, -2.0665e+00]],

         [[ 3.1214e-01,  1.6837e+00, -1.0645e+00,  ..., -9.8516e-01,
            4.3814e-01, -1.9118e+00],
          [ 3.1318e-01, -7.9201e-01,  1.3592e-01,  ...,  1.1077e+00,
            1.1985e+00, -1.8642e+00]],

         [[-8.9736e-01, -6.3391e-01,  8.2650e-01,  ...,  3.3618e-01,
            7.8628e-01, -6.8203e-01],
          [-1.1126e+00, -8.4452e-01,  1.6819e+00,  ..., -1.2043e+00,
            2.0258e+00, -1.4443e+00]]],


        [[[-2.7471e-01, -3.4588e-01,  5.0534e-02,  ...,  1.4485e+00,
           -3.1027e-01, -1.2747e+00],
          [-2.5288e-01,  3.5484e-01,  7.0041e-01,  ...,  1.0890e+00,
            2.1885e+00, -1.8425e+00]],

         [[-8.1837e-01, -2.9209e-01, -1.5490e+00,  ..., -1.4206e+00,
            8.7579e-01, -1.2668e+00],
          [-3.5026e-01, -7.4112e-01,  1.1139e+00,  ...,  3.4873e-01,
            2.9099e+00, -5.6277e-01]],

         [[-1.1638e+00, -1.3308e+00,  1.2314e+00,  ..., -2.2807e+00,
            1.3237e+00, -2.2372e+00],
          [ 4.2490e-01,  1.4729e-02, -1.4874e+00,  ...,  6.6220e-01,
            1.4889e+00, -1.0370e+00]],

         ...,

         [[-1.3038e+00,  5.1345e-01,  6.4543e-02,  ..., -2.6641e-01,
           -1.0063e+00, -8.2978e-01],
          [ 1.8732e+00, -1.6994e+00,  3.8266e-01,  ..., -6.7758e-03,
            2.1404e+00, -1.6559e+00]],

         [[-1.8421e-01,  1.2361e+00, -2.2874e-01,  ..., -2.6580e-01,
           -1.0398e-01, -1.5586e+00],
          [ 4.1595e-01, -1.7067e+00,  7.9590e-01,  ...,  2.9266e-01,
            9.1149e-01, -1.1649e+00]],

         [[-8.9736e-01, -6.3391e-01,  8.2650e-01,  ...,  3.3618e-01,
            7.8628e-01, -6.8203e-01],
          [-1.1126e+00, -8.4452e-01,  1.6819e+00,  ..., -1.2043e+00,
            2.0258e+00, -1.4443e+00]]]], grad_fn=<ViewBackward0>)
tensor([[[-0.2309, -0.5601, -1.0657,  ...,  0.0742, -0.0798, -0.2252],
         [ 0.1049, -0.4386, -0.4372,  ..., -0.4451,  0.0560, -0.3899],
         [ 0.3035, -0.4815, -0.3939,  ..., -0.0487, -0.2804, -0.4662],
         ...,
         [-0.1700, -0.2141, -0.4073,  ..., -0.4912, -0.4891, -0.3440],
         [ 0.2550, -0.1190, -0.6505,  ..., -0.0568,  0.0731, -0.4519],
         [ 0.9059,  0.0416, -0.3623,  ..., -0.6127, -0.6127, -0.5601]],

        [[-0.2309, -0.5601, -1.0657,  ...,  0.0742, -0.0798, -0.2252],
         [ 0.2811, -0.5532, -0.3754,  ..., -0.2030, -0.3061, -0.7569],
         [ 0.8530, -0.2219, -0.8702,  ...,  0.2913, -0.6175, -0.7413],
         ...,
         [-0.1406, -0.7801, -0.1068,  ..., -0.1468, -0.3293,  0.0031],
         [ 0.1270, -0.0845, -0.7185,  ...,  0.2879,  0.2018, -1.1517],
         [ 0.9059,  0.0416, -0.3623,  ..., -0.6127, -0.6127, -0.5601]]],
       grad_fn=<ViewBackward0>)
tensor([[[-0.2309, -0.5601, -1.0657,  ...,  0.0742, -0.0798, -0.2252],
         [ 0.1049, -0.4386, -0.4372,  ..., -0.4451,  0.0560, -0.3899],
         [ 0.3035, -0.4815, -0.3939,  ..., -0.0487, -0.2804, -0.4662],
         ...,
         [-0.1700, -0.2141, -0.4073,  ..., -0.4912, -0.4891, -0.3440],
         [ 0.2550, -0.1190, -0.6505,  ..., -0.0568,  0.0731, -0.4519],
         [ 0.9059,  0.0416, -0.3623,  ..., -0.6127, -0.6127, -0.5601]],

        [[-0.2309, -0.5601, -1.0657,  ...,  0.0742, -0.0798, -0.2252],
         [ 0.2811, -0.5532, -0.3754,  ..., -0.2030, -0.3061, -0.7569],
         [ 0.8530, -0.2219, -0.8702,  ...,  0.2913, -0.6175, -0.7413],
         ...,
         [-0.1406, -0.7801, -0.1068,  ..., -0.1468, -0.3293,  0.0031],
         [ 0.1270, -0.0845, -0.7185,  ...,  0.2879,  0.2018, -1.1517],
         [ 0.9059,  0.0416, -0.3623,  ..., -0.6127, -0.6127, -0.5601]]],
       grad_fn=<ViewBackward0>)
tensor([[[[-0.2309, -0.5601, -1.0657,  ..., -0.1054,  0.2679,  0.6791],
          [-0.5341, -0.1318, -0.0172,  ...,  0.0742, -0.0798, -0.2252]],

         [[ 0.1049, -0.4386, -0.4372,  ..., -0.4488,  0.6004,  0.4973],
          [-0.8282, -0.0819, -0.3837,  ..., -0.4451,  0.0560, -0.3899]],

         [[ 0.3035, -0.4815, -0.3939,  ..., -0.3056,  0.7212,  0.6547],
          [-1.0828,  0.0953, -0.4107,  ..., -0.0487, -0.2804, -0.4662]],

         ...,

         [[-0.1700, -0.2141, -0.4073,  ..., -0.2061,  1.0494,  0.3633],
          [-0.5473, -0.3643, -1.0202,  ..., -0.4912, -0.4891, -0.3440]],

         [[ 0.2550, -0.1190, -0.6505,  ..., -0.1798,  1.0591,  0.3134],
          [-0.4368, -0.2281, -1.0475,  ..., -0.0568,  0.0731, -0.4519]],

         [[ 0.9059,  0.0416, -0.3623,  ..., -0.5017,  0.4830,  0.3668],
          [-0.2579, -0.4592, -0.4757,  ..., -0.6127, -0.6127, -0.5601]]],


        [[[-0.2309, -0.5601, -1.0657,  ..., -0.1054,  0.2679,  0.6791],
          [-0.5341, -0.1318, -0.0172,  ...,  0.0742, -0.0798, -0.2252]],

         [[ 0.2811, -0.5532, -0.3754,  ..., -0.1045,  0.3720,  0.8030],
          [-0.4443, -0.5935, -0.6860,  ..., -0.2030, -0.3061, -0.7569]],

         [[ 0.8530, -0.2219, -0.8702,  ..., -0.1802,  0.6483,  0.5398],
          [-1.2802, -0.1124, -0.2363,  ...,  0.2913, -0.6175, -0.7413]],

         ...,

         [[-0.1406, -0.7801, -0.1068,  ..., -0.0051,  1.1110,  0.3506],
          [-0.6431,  0.0938, -0.2017,  ..., -0.1468, -0.3293,  0.0031]],

         [[ 0.1270, -0.0845, -0.7185,  ..., -0.1865,  0.7800,  0.5893],
          [-0.6582,  0.2027,  0.1155,  ...,  0.2879,  0.2018, -1.1517]],

         [[ 0.9059,  0.0416, -0.3623,  ..., -0.5017,  0.4830,  0.3668],
          [-0.2579, -0.4592, -0.4757,  ..., -0.6127, -0.6127, -0.5601]]]],
       grad_fn=<ViewBackward0>)
tensor([[[ 0.1983,  0.6882, -0.2732,  ..., -0.6521, -0.2896,  0.0453],
         [-0.1983,  0.1467, -0.2385,  ..., -0.3187, -0.0925,  0.5412],
         [ 0.1169,  0.6177,  0.0293,  ..., -0.5470, -0.5322, -0.5605],
         ...,
         [-0.4791,  0.8204, -0.0853,  ...,  0.0548, -0.3132, -0.2352],
         [-0.3726,  0.2271, -0.2601,  ..., -0.6008, -0.3107,  0.4828],
         [-0.3394,  0.3251, -0.8436,  ...,  0.1062, -0.0967, -0.4491]],

        [[ 0.1983,  0.6882, -0.2732,  ..., -0.6521, -0.2896,  0.0453],
         [-0.3150, -0.2749, -0.5294,  ..., -0.0498,  0.3865,  0.3251],
         [ 0.3297,  0.4174, -0.3031,  ..., -1.3133, -0.0190, -0.3525],
         ...,
         [-0.2929,  0.2462, -0.7371,  ...,  0.0983, -0.3728,  0.0505],
         [-0.7398,  0.2274, -0.5486,  ...,  0.3577,  0.0615, -0.3705],
         [-0.3394,  0.3251, -0.8436,  ...,  0.1062, -0.0967, -0.4491]]],
       grad_fn=<ViewBackward0>)
tensor([[[ 0.1983,  0.6882, -0.2732,  ..., -0.6521, -0.2896,  0.0453],
         [-0.1983,  0.1467, -0.2385,  ..., -0.3187, -0.0925,  0.5412],
         [ 0.1169,  0.6177,  0.0293,  ..., -0.5470, -0.5322, -0.5605],
         ...,
         [-0.4791,  0.8204, -0.0853,  ...,  0.0548, -0.3132, -0.2352],
         [-0.3726,  0.2271, -0.2601,  ..., -0.6008, -0.3107,  0.4828],
         [-0.3394,  0.3251, -0.8436,  ...,  0.1062, -0.0967, -0.4491]],

        [[ 0.1983,  0.6882, -0.2732,  ..., -0.6521, -0.2896,  0.0453],
         [-0.3150, -0.2749, -0.5294,  ..., -0.0498,  0.3865,  0.3251],
         [ 0.3297,  0.4174, -0.3031,  ..., -1.3133, -0.0190, -0.3525],
         ...,
         [-0.2929,  0.2462, -0.7371,  ...,  0.0983, -0.3728,  0.0505],
         [-0.7398,  0.2274, -0.5486,  ...,  0.3577,  0.0615, -0.3705],
         [-0.3394,  0.3251, -0.8436,  ...,  0.1062, -0.0967, -0.4491]]],
       grad_fn=<ViewBackward0>)
tensor([[[[ 1.9827e-01,  6.8824e-01, -2.7316e-01,  ..., -7.2900e-01,
            1.0510e+00, -3.0085e-01],
          [-3.4246e-01,  2.4491e-01,  3.5866e-01,  ..., -6.5211e-01,
           -2.8958e-01,  4.5348e-02]],

         [[-1.9827e-01,  1.4674e-01, -2.3846e-01,  ..., -2.6557e-01,
            5.7602e-01, -7.1520e-01],
          [-5.9118e-01, -1.6601e-02,  4.0684e-02,  ..., -3.1872e-01,
           -9.2503e-02,  5.4121e-01]],

         [[ 1.1687e-01,  6.1768e-01,  2.9307e-02,  ...,  1.6364e-01,
            9.1020e-02, -1.7956e-01],
          [ 5.8746e-01,  7.4986e-01,  7.4175e-02,  ..., -5.4701e-01,
           -5.3217e-01, -5.6051e-01]],

         ...,

         [[-4.7908e-01,  8.2041e-01, -8.5291e-02,  ...,  4.5333e-01,
            1.7732e-01, -5.1596e-01],
          [ 6.2775e-01,  6.8450e-01, -3.0606e-01,  ...,  5.4836e-02,
           -3.1324e-01, -2.3519e-01]],

         [[-3.7255e-01,  2.2709e-01, -2.6014e-01,  ..., -8.1512e-01,
            1.5971e-01, -1.2022e-03],
          [ 3.9705e-01,  1.6222e-01,  1.1673e-01,  ..., -6.0080e-01,
           -3.1069e-01,  4.8282e-01]],

         [[-3.3937e-01,  3.2507e-01, -8.4364e-01,  ..., -3.5962e-01,
           -2.6420e-03, -7.2943e-01],
          [ 1.3922e-01,  2.7979e-01, -1.1959e-01,  ...,  1.0622e-01,
           -9.6664e-02, -4.4909e-01]]],


        [[[ 1.9827e-01,  6.8824e-01, -2.7316e-01,  ..., -7.2900e-01,
            1.0510e+00, -3.0085e-01],
          [-3.4246e-01,  2.4491e-01,  3.5866e-01,  ..., -6.5211e-01,
           -2.8958e-01,  4.5348e-02]],

         [[-3.1503e-01, -2.7488e-01, -5.2938e-01,  ..., -2.1594e-01,
            2.2773e-01,  1.4663e-01],
          [-9.4616e-02, -5.4614e-02,  9.8546e-02,  ..., -4.9787e-02,
            3.8651e-01,  3.2505e-01]],

         [[ 3.2973e-01,  4.1736e-01, -3.0309e-01,  ..., -5.6368e-01,
            4.4954e-01,  1.5917e-01],
          [ 6.6490e-01,  7.1750e-01,  5.8053e-01,  ..., -1.3133e+00,
           -1.8970e-02, -3.5249e-01]],

         ...,

         [[-2.9294e-01,  2.4624e-01, -7.3712e-01,  ...,  1.1108e-01,
            8.5193e-01, -6.0799e-01],
          [ 2.8262e-01,  5.2614e-01, -2.0426e-01,  ...,  9.8276e-02,
           -3.7279e-01,  5.0505e-02]],

         [[-7.3982e-01,  2.2745e-01, -5.4858e-01,  ..., -2.4658e-01,
           -4.9798e-01,  1.0628e+00],
          [-7.0543e-02,  3.3284e-01, -1.3428e-01,  ...,  3.5773e-01,
            6.1528e-02, -3.7052e-01]],

         [[-3.3937e-01,  3.2507e-01, -8.4364e-01,  ..., -3.5962e-01,
           -2.6419e-03, -7.2943e-01],
          [ 1.3922e-01,  2.7979e-01, -1.1959e-01,  ...,  1.0622e-01,
           -9.6664e-02, -4.4909e-01]]]], grad_fn=<ViewBackward0>)
tensor([[[[-0.2663,  0.3452, -0.1528,  ..., -0.4028,  0.3969, -0.2096],
          [-0.2853,  0.3786, -0.2007,  ..., -0.4426,  0.3604, -0.1813],
          [-0.3196,  0.3412, -0.1486,  ..., -0.4040,  0.3307, -0.1663],
          ...,
          [-0.2893,  0.3611, -0.1565,  ..., -0.3946,  0.3394, -0.1886],
          [-0.2778,  0.3831, -0.1553,  ..., -0.4001,  0.3533, -0.1666],
          [-0.3054,  0.3529, -0.1805,  ..., -0.4377,  0.3390, -0.1708]],

         [[ 0.0284,  0.3996, -0.0010,  ..., -0.4163, -0.2391, -0.0756],
          [-0.0233,  0.3302, -0.0026,  ..., -0.3282, -0.2366, -0.0196],
          [-0.0821,  0.2870, -0.0073,  ..., -0.3086, -0.2101,  0.0313],
          ...,
          [-0.0160,  0.2885, -0.0350,  ..., -0.2781, -0.2338,  0.0060],
          [ 0.0350,  0.3472, -0.0111,  ..., -0.3291, -0.2572, -0.0418],
          [ 0.0143,  0.3417, -0.0353,  ..., -0.2626, -0.2566, -0.0796]]],


        [[[-0.5264,  0.2003, -0.1399,  ..., -0.1761,  0.1286,  0.1534],
          [-0.4171,  0.2529, -0.2961,  ..., -0.2563,  0.1658,  0.1408],
          [-0.4330,  0.1948, -0.1855,  ..., -0.1786,  0.1910,  0.1190],
          ...,
          [-0.3665,  0.3305, -0.2756,  ..., -0.3121,  0.3089, -0.0472],
          [-0.4166,  0.1689, -0.1421,  ..., -0.2038,  0.1557,  0.1240],
          [-0.3769,  0.2557, -0.2082,  ..., -0.2870,  0.2518,  0.0178]],

         [[ 0.0948,  0.5248, -0.0037,  ..., -0.2963, -0.0060, -0.2141],
          [-0.0580,  0.4715, -0.1569,  ..., -0.1519, -0.0377, -0.0840],
          [-0.0369,  0.4612, -0.1000,  ..., -0.1340, -0.0082, -0.1293],
          ...,
          [ 0.0109,  0.4697, -0.1071,  ..., -0.1700, -0.0605, -0.1123],
          [-0.0159,  0.4842, -0.0871,  ..., -0.2403, -0.0048, -0.1243],
          [-0.0193,  0.5199, -0.1376,  ..., -0.2356, -0.0166, -0.1199]]]],
       grad_fn=<ScaledDotProductFlashAttentionForCpuBackward0>)
tensor([[[[-0.2663,  0.3452, -0.1528,  ..., -0.4028,  0.3969, -0.2096],
          [ 0.0284,  0.3996, -0.0010,  ..., -0.4163, -0.2391, -0.0756]],

         [[-0.2853,  0.3786, -0.2007,  ..., -0.4426,  0.3604, -0.1813],
          [-0.0233,  0.3302, -0.0026,  ..., -0.3282, -0.2366, -0.0196]],

         [[-0.3196,  0.3412, -0.1486,  ..., -0.4040,  0.3307, -0.1663],
          [-0.0821,  0.2870, -0.0073,  ..., -0.3086, -0.2101,  0.0313]],

         ...,

         [[-0.2893,  0.3611, -0.1565,  ..., -0.3946,  0.3394, -0.1886],
          [-0.0160,  0.2885, -0.0350,  ..., -0.2781, -0.2338,  0.0060]],

         [[-0.2778,  0.3831, -0.1553,  ..., -0.4001,  0.3533, -0.1666],

INFO     Pruning module: bert_encoder_layer_0_attention_self_key
INFO     Pruning module: bert_encoder_layer_0_attention_self_value
INFO     Pruning module: bert_encoder_layer_0_attention_output_dense
INFO     Pruning module: bert_encoder_layer_0_intermediate_dense
INFO     Pruning module: bert_encoder_layer_0_output_dense
INFO     Pruning module: bert_encoder_layer_1_attention_self_key
INFO     Pruning module: bert_encoder_layer_1_attention_output_dense
INFO     Pruning module: bert_encoder_layer_1_intermediate_dense
INFO     Pruning module: bert_encoder_layer_1_output_dense
INFO     Pruning module: bert_pooler_dense
INFO     Pruning module: classifier

Finally, export the MaseGraph for the compressed checkpoint to be used in future tutorials for hardware generation and distributed deployment.

In [12]:
mg.export(f"{Path.home()}/tutorial_5_nas_compressed", save_format="state_dict")

INFO     Exporting MaseGraph to /home/roy/tutorial_5_nas_compressed.pt, /home/roy/tutorial_5_nas_compressed.mz
INFO     Exporting GraphModule to /home/roy/tutorial_5_nas_compressed.pt
INFO     Saving state_dict format
INFO     Exporting MaseMetadata to /home/roy/tutorial_5_nas_compressed.mz
WARNING  Failed to pickle call_function node: finfo
WARNING  cannot pickle 'torch.finfo' object
WARNING  Failed to pickle call_function node: getattr_3
WARNING  cannot pickle 'torch.finfo' object